# This is a sample config.toml document for EOSIO DSPs

[dsp]
# enter account
account = "<DSP ACCOUNT>"
# enter account private key
private_key = "<DSP PRIVATE KEY>"
port = 3115
# configure available services: (comment for all services)
# services_enabled = "ipfs,log,vaccounts,oracle,cron,readfn,auth,storage,history,sign"
# account_permissions = "active"

[nodeos]
host = "localhost"
port = 8888
secured = false

# mainnet:
chainid = "aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906"
# kylin: "5fff1dae8dc8e2fc4d5b23b2c7665c97f9e9d8edf2b6485a86ba311c25639191"

# if using zmq_plugin: 
zmq_port = 5557
# if using state_history_plugin: 
websocket_port = 8887

host_dsp = "localhost"
host_dsp_port = 3115

[demux]
backend = "state_history_plugin"
# zmq: "zmq_plugin" only if using nodeos with eosrio's version of the ZMQ plugin: https://github.com/eosrio/eos_zmq_plugin
socket_mode = "sub"
# head block to sync demux from
head_block = 35000000

[ipfs]
protocol = "http"
host = "localhost"
port = 5001