# This is a sample config.toml document for EOSIO DSPs

[dsp]
# enter account
account = "<DSP ACCOUNT>"
# enter account private key
private_key = "<DSP PRIVATE KEY>"
port = 3115
# configure available services: (comment for all services)
# services_enabled = "ipfs,log,vaccounts,oracle,cron,readfn,auth,storage,history,sign"
# account_permissions = "active"
# consumer_pays: setting this to true forces consumer to pay for all cpu/net/ram
# however, if they don't have the correct permission setup, everything will fail
# review consumer pays documentation prior to setting this to true
consumer_pays = false

[database]
# url syntax: postgres://user:pass@example.com:5432/dbname
url = "postgres://user:pass@example.com:5432/dbname"

# production (uses above url for database)
node_env = "production"

[nodeos]
host = "localhost"
port = 8888
secured = false

# mainnet:
chainid = "aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906"
# kylin: "5fff1dae8dc8e2fc4d5b23b2c7665c97f9e9d8edf2b6485a86ba311c25639191"

# if using state_history_plugin: 
websocket_port = 8887

[demux]
socket_mode = "sub"
# head block to sync demux from
head_block = 35000000
# demux defaults to first pulling head block from toml file if postgres database is not set
# after database is set, defaults to databse, to overwrite and default to toml file, pass true
bypass_database_head_block = false

[ipfs]
protocol = "http"
host = "localhost"
port = 5001

# sidechain section, if no sidechains, leave as [sidechains], can add additional sidechains with [sidechains.newchain] ...
[sidechains]
  [sidechains.test1]
    # dsp
    dsp_port = 3116
    dsp_account = "test1"
    dsp_private_key = ""
    # nodeos
    nodeos_host = "localhost"
    nodeos_port = 8888
    nodeos_secured = false
    nodeos_chainid = ""
    nodeos_websocket_port = 8887
    webhook_dapp_port = 8113
    # demux
    demux_webhook_port = 3196
    demux_socket_mode = "sub"
    demux_head_block = 1
    # demux defaults to first pulling head block from toml file if postgres database is not set
    # after database is set, defaults to databse, to overwrite and default to toml file, pass true
    demux_bypass_database_head_block = false
    # sidechain 
    liquidx_contract = "liquidxxxxxx"
    name = "test1"
    # the mapping below contains the dappservices:dappservicex, mainnet_dsp:new_chain_dsp, and mainnet_service_contract:new_chain_service_contract mappings
    mapping = "dappservices:dappservicex,heliosselene:heliosselene,uuddlrlrbass:uuddlrlrbass,cronservices:cronservices,ipfsservice1:ipfsservice1,readfndspsvc:readfndspsvc,logservices1:logservices1,oracleservic:oracleservic,accountless1:accountless1,liquidstorag:liquidstorag,authfndspsvc:authfndspsvc,vcpuservices:vcpuservices"
