# This is a sample config.toml document for EOSIO DSPs

[dsp]
account = "<DSP ACCOUNT>"
private_key = "<DSP PRIVATE KEY>"
port = 3115

[nodeos]
host = "localhost"
port = 8888
secured = false
chainid = "aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906"
zmq_port = 5557
websocket_port = 8887

host_dsp = "localhost"
host_dsp_port = 3115

[demux]
backend = "state_history_plugin"
socket_mode = "sub"

[ipfs]
protocol = "http"
host = "localhost"
port = 5001
